- test/test_api.py
this new method saves 2-5 lines of code for each tests. While not
extremely optimized yet, it's still an improvement over the old/verbose
approach.
> Simplified api tests with addition of a helper method

- README.md
- conjur_api_python3/api.py
- conjur_api_python3/cli.py
- conjur_api_python3/client.py
- conjur_api_python3/endpoints.py
- conjur_api_python3/http.py
- pkg_bin/conjur-py3-cli
- test/test_api.py
- test/test_cli.py
- test/test_cli_integration.py
- test/test_client.py
- test/test_endpoints.py
- test/test_http.py
- test/util/cli_helpers.py
This PR adds the capability to fetch multiple secrets at the same time through the API to reduce overhead
> `get many` feature

- .coveragerc
- .gitignore
- Jenkinsfile
- bin/test_unit
- conjur_api_python3/cli.py
- conjur_api_python3/http.py
- requirements.txt
- test/test_api.py
- test/test_cli_integration.py
- test/test_client.py
- test/test_http.py
- unittest.cfg
We now have visibility into what code is not being adequately tested or
checked. Any issues found during the enabling of this feature has been
integrated too so that we can have the highest targets possible.
Build: https://jenkins.conjur.net/job/conjurinc--conjur-api-python3/job/coverage/
> Added coverage report to the repository

- .gitignore
- CHANGELOG.md
- Jenkinsfile
- README.md
- conjur_api_python3/api.py
- conjur_api_python3/cli.py
- conjur_api_python3/client.py
- conjur_api_python3/version.py
- test/test_api.py
- test/test_cli.py
- test/test_cli_integration.py
- test/test_client.py
- test/test_config/policies/users.yml
- test/util/cli_helpers.py
We now properly output results from apply and replace policy invocations
> Add policy change output support

- .gitleaks.toml
- Jenkinsfile
* submit coverage results to CodeClimate
* Add gitleaks.toml config file
Related: conjurinc/ops#233
> Submit CodeClimate Coverage

- CHANGELOG.md
- conjur/http.py
- test/test_http.py
This should fix the escaping issues in login_id and we prepare for the release with this PR since this needs to get to PIP asap.
> Fix slash escaping

- CHANGELOG.md
- conjur/version.py
The change here is signifficant enough to warrant a new release.
> Prepare for v0.0.5 release

- CHANGELOG.md
- conjur/version.py
The links were updated and date added to 1.0.0 tag.
> Updated CHANGELOG to prepare for v0.1.0 release

- README.md
It's nice to see a visual representation of these values instantly when
checking out the project.
> Added CodeClimate badges to readme

- Jenkinsfile
Set trivy scanning to CRITICAL
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
> Set trivy to flag CRITICAL

- bin/publish_container
Temporarily disabled until project reaches appropriate certification level
N/A
> Disable publishing to DockerHub

- README.md
- conjur/api.py
- conjur/cli.py
- conjur/client.py
- conjur/endpoints.py
- docker-compose.yml
- test/test_api.py
- test/test_cli.py
- test/test_cli_integration.py
- test/test_client.py
- test/test_endpoints.py
- test/util/cli_helpers.py
- _What's changed? Why were these changes made?
Added `whoami` API call to Conjur client and its test
> Added whoami api call to Conjur client

- test/test_client.py
> Renamed test

- test/test_cli.py
Fixed issues with test name repetitions
> Renamed whoami tests

- requirements.txt
- setup.py
We were quite a bit behind on these so this PR bumps them all to recent
versions.
N/A
> Update dependencies of the project

- design/variable_command_design.md
Adds design for variable CLI command
> Add variable CLI command design

- design/list_command_design.md
> Add list command design

- design/deployment_design.md
Adds deployment design document
MD: https://github.com/cyberark/conjur-api-python3/blob/add_deployment_design/design/deployment_design.md
> Add deployment design document

- conjur/cli.py
- test/test_cli.py
Remove Python string and add copyright tests
> Remove Python string and add copyright tests

- Jenkinsfile
- conjur/api.py
- conjur/cli.py
- conjur/client.py
- conjur/constants.py
- conjur/init/init_controller.py
- test/test_init_controller.py
- test/test_init_logic.py
- test/test_ssl_service.py
This PR fixes the bugs that were found from our manual tests
> Bug fixes found from init manual tests

- Jenkinsfile
- conjur/cli.py
- conjur/client.py
- conjur/credentials_from_file.py
- conjur/logout/logout_controller.py
- conjur/logout/logout_logic.py
- test/test_config/conjur_policy.yml
- test/test_config/host_policy.yml
- test/test_integration_configurations.py
- test/test_integration_credentials.py
- test/test_unit_client.py
Add integration tests for login/logout
> Add integration tests for login/logout command

- Utils/py_utils.py
- conjur/cli.py
- conjur/constants.py
- test/test_config/conjurrc
- test/test_integration_cli.py
- test/test_integration_configurations.py
- test/test_integration_credentials.py
- test/test_integration_oss.py
- test/util/cli_helpers.py
- test/util/models/configfile.py
- test/util/test_path_provider.py
- test/util/test_runners/integration_test_case.py
- test/util/test_runners/integrations_tests_runner.py
- test/util/test_runners/params.py
- test/util/test_runners/test_runner_args.py
- Added the capability to run integration tests as a process
- Please look at the new design. think of a ways it can hurt us in the future
Should open a ticket on this.
> Integration tests as a process

- test/test_config/conjurrc
- test/util/test_path_provider.py
- test/util/test_runners/integrations_tests_runner.py
- test/util/test_runners/params.py
- test/util/test_runners/test_runner_args.py
- Code refactoring, added param to run oss integration tests 
- Please run on your side that everything indeed works?
> Update process flow

- Utils/py_utils.py
- conjur/cli.py
- conjur/client.py
- conjur/list/list_data.py
- conjur/list/list_logic.py
Updates the list object representation to align the object and the way we print the object
> Update representation of list object

- CHANGELOG.md
- Utils/py_utils.py
- conjur/api.py
- conjur/argparse_wrapper.py
- conjur/cli.py
- conjur/client.py
- conjur/http.py
- conjur/policy/__init__.py
- conjur/policy/policy_controller.py
- conjur/policy/policy_data.py
- conjur/policy/policy_logic.py
- conjur/variable/__init__.py
- conjur/variable/variable_controller.py
- conjur/variable/variable_data.py
- conjur/variable/variable_logic.py
- test/test_config/variable_policy.yml
- test/test_integration_cli.py
- test/test_integration_configurations.py
- test/test_integration_credentials.py
- test/test_integration_list.py
- test/test_integration_oss.py
- test/test_integration_policy.py
- test/test_integration_variable.py
- test/test_unit_api.py
- test/test_unit_cli.py
- test/test_unit_client.py
- test/util/cli_helpers.py
- test/util/test_runners/integration_test_case.py
- test/util/test_runners/integrations_tests_runner.py
Adds policy + variable integration tests
Refactors policy + variable into their own classes
Resolves #138, #90
> Add variable logic and integration tests

- CHANGELOG.md
- Utils/py_utils.py
- conjur/cli.py
- conjur/client.py
- conjur/credentials_from_file.py
- conjur/init/init_controller.py
- conjur/login/login_controller.py
- conjur/logout/logout_controller.py
- test/test_integration_credentials.py
- test/test_integration_list.py
- test/test_integration_resource.py
- test/test_integration_variable.py
- test/test_unit_cli.py
- test/util/test_runners/integrations_tests_runner.py
This PR implements the UX according to the guidelines described here https://ljfz3b.axshare.com/#id=x8ktq8&p=conjur_help__init&g=1
To review, pack the CLI `pyinstaller -D ./pkg_bin/conjur` and launch commands according to the UX in above link
Resolves #132
> Add improved UX for implemented commands

- conjur/api.py
- conjur/cli.py
- conjur/client.py
- conjur/errors.py
- conjur/host/host_controller.py
- conjur/init/init_controller.py
- conjur/resource.py
- conjur/user/__init__.py
- conjur/user/user_controller.py
- conjur/user/user_input_data.py
- conjur/user/user_logic.py
- test/test_integration_resource.py
- test/test_integration_variable.py
- test/test_unit_cli.py
Additional feedback was received on the user/host commands. For the sake of an easier review process, I am creating a new PR that addresses the feedback
> Implements additional feedback from user/host commands

- conjur/cli.py
- conjur/errors.py
- conjur/host/host_controller.py
- conjur/init/init_controller.py
- conjur/login/login_controller.py
- conjur/policy/policy_controller.py
- conjur/user/user_controller.py
- test/test_integration_configurations.py
- test/test_unit_cli.py
Implements second round of UX feedback
Executable can be found here:
[conjur-cli-round-2.tar.gz](https://github.com/cyberark/conjur-api-python3/files/5899888/conjur-cli-round-2.tar.gz)
> Implement UX improvements

- LICENSE.md
- NOTICES.md
- README.md
This PR adds the NOTICES.md file and adds the Cyberark copyright to readmine
Resolves #111
> Add NOTICES and copyright to repository

- conjur/__init__.py
- conjur/__main__.py
- conjur/init/__init__.py
- conjur/list/__init__.py
- conjur/login/__init__.py
- conjur/logout/__init__.py
- test/test_integration_policy.py
As part of the refactoring effort . Changed all implicit import statements to explicit ones. You can read more about in [General Refactor Plan](https://github.com/cyberark/conjur-api-python3/blob/master/design/general_refactorings.md#explicit-import-statements)
[Resolves Issue 121](https://github.com/cyberark/conjur-api-python3/issues/121)
> Change implicit imports to explicit

- CONTRIBUTING.md
This PR fixes the broken NOTICES link on the CONTRIBUTING.md page
> Fix broken NOTICES link

- CONTRIBUTING.md
- NOTICES.md
- NOTICES.txt
- requirements.txt
Add license of cryptography lib. Lib added temporarily to be a strict version here :  https://github.com/cyberark/conjur-api-python3/pull/183/files
- [] The CHANGELOG has been updated, or
> Add license of cryptography lib

- conjur/api/client.py
- conjur/cli.py
- conjur/constants.py
- conjur/controller/init_controller.py
- conjur/controller/login_controller.py
- conjur/controller/user_controller.py
- conjur/errors.py
- conjur/errors_messages.py
- conjur/logic/init_logic.py
- conjur/logic/login_logic.py
- conjur/wrapper/http_wrapper.py
- docker-compose.yml
- test/test_integration_credentials.py
- test/test_integration_resource.py
- test/test_unit_cli.py
- test/test_unit_client.py
- test/test_unit_http.py
- test/test_unit_init_controller.py
- test/test_unit_login_controller.py
- test/test_unit_login_logic.py
- test/util/test_runners/test_runner_args.py
Previously we were getting a warning
```
2021-02-18 15:44:21,794 WARNING: Certificate did not match expected hostname: ec2-54-237-48-3.compute-1.amazonaws.com. Certificate: {'subject': ((('commonName', 'localhost'),),), 'issuer': ((('organizationName', 'cucumber'),), (('organizationalUnitName', 'Conjur CA'),), (('commonName', 'localhost'),)), 'version': 3, 'serialNumber': 'C510B5A5BB649B524E5E0D3F105365BC05C0BB24', 'notBefore': 'Feb 17 07:25:28 2021 GMT', 'notAfter': 'Feb 15 07:25:28 2031 GMT', 'subjectAltName': (('DNS', 'localhost'), ('DNS', 'localhost'), ('DNS', 'conjur'))}
```
which was not understandable. We now print both the WARNING and a more descriptive error message. 
2021-02-18 16:22:07,007 WARNING: Certificate did not match expected hostname: …
> Add more readable hostname mismatch warning and add supporting tests

- test/test_integration_configurations.py
- test/test_integration_credentials.py
Some tests were failing as a result of working with a DAP master that has a CA signed cert. This PR fixes this
> Add fix for testing as a process with CA signed certificate flow

- conjur/cli.py
The examples in the CLI help screens did not provide a password with the correct password complexity and this commit fixes these examples
Resolves #-
> Update password example to valid password

- CONTRIBUTING.md
- conjur/cli.py
- conjur/errors.py
- conjur/errors_messages.py
- conjur/wrapper/http_wrapper.py
Some changes got overwritten because of the failing build. This PR makes the changes again
Resolves -
> Unify remaining password complexity examples

- conjur/cli.py
- conjur/controller/login_controller.py
- conjur/util/util_functions.py
- test/test_unit_login_controller.py
Previously, all errors were returning 'Check your credentials' solution response regardless of the type of error being returned. This commit fixes this by differentiating between the status codes to return the relevant error message.
Resolves #223
> Update login error handling

- NOTICES.txt
We added a new library during the implementation of keyring (keyring) and we need license approval
- Add keyring license and copyright to notices file
Resolves #234
> Update license NOTICES.txt

- conjur/constants.py
- test/test_unit_credential_store_factory.py
- test/test_unit_keystore_adapter.py
- test/test_unit_keystore_credentials_provider.py
Adds unittests for the keyring feature
Resolves issue https://github.com/cyberark/conjur-api-python3/issues/247
> keyring unittests

- conjur/errors_messages.py
- conjur/wrapper/keystore_adapter.py
- test/test_integration_configurations.py
Fix minor formatting in testing files and update log message when unable to fetch credentials. 
Resolves -
> Fix minor formatting issues

- bin/test_integration
- conjur/constants.py
- conjur/controller/logout_controller.py
- conjur/errors.py
- conjur/interface/credentials_store_interface.py
- conjur/logic/credential_provider/credential_store_factory.py
- conjur/logic/credential_provider/file_credentials_provider.py
- conjur/logic/credential_provider/keystore_credentials_provider.py
- conjur/logic/login_logic.py
- conjur/logic/logout_logic.py
- conjur/util/os_types.py
- conjur/util/util_functions.py
- conjur/wrapper/keystore_adapter.py
- docker-compose.yml
- test/test_integration_credentials_keyring.py
- test/test_unit_keystore_adapter.py
- test/test_unit_keystore_credentials_provider.py
- test/test_unit_login_logic.py
- test/test_unit_logout_logic.py
***This PR is a duplication of the #255. We created a new PR because the previous PR went stale and had a lot of merge conflicts***
1) Added logic to KeystoreAdapter, to use only specific keyring per platform
2) made CredentialsStoreInterface a formal interface (if a child implementing this interface doesn't implement one of the functions we will get a runtime error)
3) Code refactoring throughout the code
1) please take a look if the refactoring make sense and better than the old ones
> Add keyring refactor and tests

- .github/CODEOWNERS
Adds the community and integrations team as codeowners to the project
Resolves #-
> Add community and integrations team as CODEOWNERS

- test/test_integration_configurations.py
- test/test_integration_credentials_keyring.py
- test/test_integration_credentials_netrc.py
- test/test_integration_list.py
- test/test_integration_oss.py
- test/test_integration_policy.py
- test/test_integration_resource.py
- test/test_integration_variable.py
- test/util/test_runners/integration_test_case.py
added some functions
- add tests for insecure mode
- please note I added TODO for the reviewer to comment
- [-] This PR does not include user-facing changes and doesn't require a CHANGELOG update
- [-] The changes in this PR do not require tests
- [-] This PR does not require updating any documentation
> added setup_insecure function for testing in insecure mode

- CONTRIBUTING.md
- README.md
- test/test_integration_configurations.py
- test/test_integration_list.py
- test/test_integration_policy.py
- test/util/test_runners/integrations_tests_runner.py
This commit updates the README docs as a result of the GA release of the CLI
> Update README for GA release

- CHANGELOG.md
- conjur/version.py
Bumps the version in the project to 7.0.1
Resolves #-
Separate PR
> Bump version for the CLI to 7.0.1

- CHANGELOG.md
- README.md
- setup.py
Changes the name of the package that will be pushed to Pypi and fixes a failure on encoding when pushing to Pypi . The README had an invalidate character.
Resolves #-
> Make minor setup file changes

- docs/Setting_3rd_party_cert_environment.md
- Add a description on how to setup testing env with 3rd party certificate
- [-] This PR does not include user-facing changes and doesn't require a CHANGELOG update
- [-] The changes in this PR do not require tests
- [-] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
> Added doc on creating third party env

- docker-compose.yml
- test/test_integration_list.py
- Upgrade conjur image version in docker-compose and adjust tests. We should be always pulling the latest version of oss and enterprise. That way, if our build fails because of a breaking change, then we address this in the next CLI release.
> Upgrade conjur image version

- CONTRIBUTING.md
Make language fixes to better clarify testing and signing processes
Resolves -
> Make clarification to testing and signing sections in contributing doc

- docs/instruction_for_testing.md
This PR adds step by step instructions for how to run integration tests
Resolves -
> Add instructions for running integration tests

- test/test_config/https/README.md
> Update link to use main branch

- README.md
- test/test_config/https/README.md
Change DAP name to Conjur in our code
https://github.com/cyberark/conjur-api-python3/issues/296
> Change DAP to Conjur

- CONTRIBUTING.md
We now ship a 'tar.gz' archive for RHEL so we need to
update the guidelines
> Update RHEL artifacts to tar.gz

- bin/test_integration_rhel8
- test/configure_test_executor.sh
This command has the admin password so it's best
not to print it
> Do not print evoke configure command

- Jenkinsfile
Previously the team would be notified for failures on 'master'. Since this was updated to 'main' we need to update the branch we want to be notified upon failure
Resolves -
> Update branch to notify errors

- CONTRIBUTING.md
This commit cleans up contributing docs to make the testing and releasing process clearer
Resolves -
> Clean up CONTRIBUTING docs

- Dockerfile.test.rhel7
- Dockerfile.test.rhel8
- Jenkinsfile
- bin/build_integrations_tests_runner
- bin/test_integration_rhel
- conjur/argument_parser/parser_utils.py
- conjur/wrapper/http_wrapper.py
- docker-compose.yml
- test/CentOS-7-Linux-AppStream.repo
- test/CentOS-Linux-AppStream.repo
- test/CentOS-SCLo-scl-rh.repo
As part of automating our tests, we need to add the ability to run our tests on RHEL 7. 
Added new files:
- RHEL 7 dockerfile (downloads and compiles Python3.9 make all libs available for pyinstaller)
- Centos repo files
- repo public keyfiles (for GPG check)
- Turned on RHEL 8 repo GPG check
[https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-11327](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-11327)
> Add RHEL 7 test flow to automation

- conjur/api/api.py
- conjur/argument_parser/_hostfactory_parser.py
- conjur/cli.py
- conjur/controller/hostfactory_controller.py
- conjur/data_object/create_token_data.py
- conjur/logic/hostfactory_logic.py
- conjur/wrapper/http_wrapper.py
- test/test_unit_api.py
- test/test_unit_cli.py
- test/test_unit_client.py
- test/test_unit_hostfactory_controller.py
- test/test_unit_hostfactory_logic.py
Adds UTs for hostfactory 'create token' command
Resolves #JIRA
> Add UTs for hostfactory 'create token' command

- conjur/controller/hostfactory_controller.py
- conjur/data_object/create_token_data.py
- test/test_integration_hostfactory.py
- test/test_unit_api.py
- test/test_unit_cli.py
- test/test_unit_client.py
- test/test_unit_hostfactory_controller.py
- test/test_unit_hostfactory_logic.py
Add UTs and integration tests for hostfactory 'create token' command
Resolves JIRA
> Add tests for cidr, count, duration flags to hostfactory

- conjur/argument_parser/_hostfactory_parser.py
- conjur/argument_parser/parser_utils.py
Align hostfactory help according to https://ca-il-confluence.il.cyber-ark.com/display/rndp/New+CLI+commands+help+text+review#/expand-hostfactory
Resolves [ONYX-13132](https://ca-il-jira.il.cyber-ark.com:8443/secure/RapidBoard.jspa?rapidView=1475&view=detail&selectedIssue=ONYX-13132)
merged.*
changes, or
- [v ] The changes in this PR do not require tests
- [v ] This PR does not require updating any documentation
- [v ] No behavior was changed with this PR
- [v ] There are no security aspects to these changes
> Hostfactorey help alignment

- conjur/api/api.py
- conjur/api/client.py
- conjur/api/endpoints.py
- conjur/argument_parser/_list_parser.py
- conjur/cli.py
- conjur/controller/host_controller.py
- conjur/controller/list_controller.py
- conjur/data_object/list_permitted_roles_data.py
- conjur/errors.py
- conjur/logic/list_logic.py
- conjur/logic/user_logic.py
- conjur/resource.py
- test/test_config/list_permitted_roles_policy.yml
- test/test_integration_list_permitted_roles.py
- test/test_unit_api.py
- test/test_unit_conjur_resource.py
- test/test_unit_host_controller.py
Add support to `--permitted-roles` arg to `list` command
merged.*
changes, or
> Add support to `--permitted-roles` arg to `list` command

- conjur/argument_parser/_hostfactory_parser.py
- conjur/controller/hostfactory_controller.py
- test/host_factory/test_integration_hostfactory_host.py
- test/host_factory/test_integration_hostfactory_token.py
All technical-writer logs reviewed
> hostfactory TW review

- conjur/api/client.py
- conjur/argument_parser/_list_parser.py
- conjur/resource.py
Text changes according to TW comments on PR #358 
merged.*
changes, or
> Fix text according to TW comments

- CHANGELOG.md
- conjur/api/__init__.py
- conjur/api/client.py
- conjur/api/errors.py
- conjur/api/models/ssl_verification_modes.py
- conjur/api/ssl_utils/errors.py
- conjur/api/ssl_utils/ssl_client.py
- conjur/api/ssl_utils/ssl_consts.py
- conjur/argument_parser/_init_parser.py
- conjur/argument_parser/_screen_options_parser.py
- conjur/cli.py
- conjur/cli_actions.py
- conjur/controller/init_controller.py
- conjur/controller/logout_controller.py
- conjur/errors.py
- conjur/logic/credential_provider/file_credentials_provider.py
- conjur/logic/init_logic.py
- conjur/util/init_utils.py
- test/test_integration_configurations.py
- test/test_unit_cli.py
- test/test_unit_init_controller.py
- test/test_unit_init_logic.py
- test/test_unit_logout_controller.py
Added many changes from outside fork
* Added cli_actions module
* more robust sdk errors 
* Added verification on SSL verification method provided by the user
* Added self-signed flag
* changed --certificate to --ca-cert flag
merged.*
changes, or
> Support multiple ssl verification flows

- Dockerfile
Publish step in pipeline needs `curl` to download pyenv.
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
merged.*
changes, or
> Fix Publish in pipeline

- Dockerfile
- Dockerfile.test
- test/test_integration_openssl.py
CLI is shipped with openssl version > 1.1.1k.
Upgraded ubuntu image version in docker files
CyberArk internal issue link: [#14467](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14467)
merged.*
changes, or
> Test open ssl version

- CHANGELOG.md
- Dockerfile.publish
- conjur/version.py
*Release will be ready after this merge
changing version number and adding dockerfile.publish file
> Set version to 7.1.0 and fix publishing

- README.md
Readme file should include sdk functionality that wasn't added after implementation
Added new functions documantations.
the rest of the changes is just side effects of line-length increase restrictions and does not have any effect on the readme UI
changes, or
> Added new sdk functions to README.md

- .github/CODEOWNERS
This project will now be managed only by the C&I team
> Remove palm-tree from code owners

- CHANGELOG.md
- CONTRIBUTING.md
Fix #405.
[Official docs](https://docs.conjur.org/Latest/en/Content/Developer/CLI/cli-setup.htm?tocpath=Developer%7CConjur%20CLI%7C_____1) must also be updated when this is released.
- Added the `z` option to the `tar` command for REHL release in CONTRIBUTING.md
Resolves #405
changes, or
> Fix tar command for RHEL release

- conjur/argument_parser/_check_parser.py
- conjur/argument_parser/argparse_builder.py
- conjur/cli.py
- conjur/cli_actions.py
- conjur/controller/check_controller.py
- conjur/logic/check_logic.py
- test/test_config/check_policy.yml
- test/test_integration_check.py
- test/test_unit_check_controller.py
- test/test_unit_check_logic.py
Added functionality for the check command in the CLI side
- Updated cli_actions.py
- Updated cli.py
- Updated requirements.txt by pointing GitHub link to my API branch
- Updated argparse_builder.py
- Created check_controller.py
- Created check_logic.py
- Created _check_parser.py
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23082;jsessionid=0B41722EE2AFAB74C1C659FC90448DBE
> Implements 'check' command in CLI

- CONTRIBUTING.md
Updated CONTRIBUTING.md to add instructions for how to ensure Python is installed with the correct parameters for pyinstaller when using pyenv. Also add link to internal docs regarding creating and signing .dmg file.
Supports [ONYX-24157](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-24157)
changes, or
> Update Mac OS build docs

- CONTRIBUTING.md
- design/authn-ldap.md
- design/authn-oidc.md
- requirements.txt
- setup.py
- test/host_factory/test_integration_hostfactory_host.py
CyberArk internal issue ID: ONYX-28511
> Docs update
