cyberark/cyberark-conjur-cli

README.md, conjur_api_python3/api.py, conjur_api_python3/cli.py, conjur_api_python3/client.py, test/test_api.py, test/test_cli.py, test/test_cli_integration.py, test/test_client.py
This adds the ability to replace a policy defined in Conjur in both the API and CLI
=> Add policy replace

requirements.txt
Urllib3 had CVE-2019-11324 that `requests` uses so we now pin for the
fixed version to ensure we don't get the faulty dependency.
https://github.com/kennethreitz/requests/issues/5065
=> Fix upstream CVE-2019-11324 issue

CHANGELOG.md, conjur/client.py, conjur/version.py, test/test_client.py
Fixes #14 
We now properly override `None` values in `Client` initialization with the ones from conjurrc.
CC: @AndrewCopeland
=> 14 - Fix conjurrc empty value overrides

CHANGELOG.md, Dockerfile.test, conjur/api.py, conjur/client.py, conjur/http.py, conjur/version.py, test/test_client.py, test/test_config.py
Old code was effectively hardcoded to always use "default" as the
account name when an account name was not provided, including times
where this data was supposed to be pulled from .conjurrc. This change
ensures that we only default the account name iff it's the only filed
missing from a valid configuration.
Connected to #21
=> Fix conjurrc account parsing logic

README.md, conjur/api.py, conjur/cli.py, conjur/client.py, conjur/http.py, test/test_api.py, test/test_cli.py, test/test_cli_integration.py, test/test_client.py, test/test_http.py, test/util/cli_helpers.py
Now we will be able to perform the PATCH method when
loading in policy which allows the ability to explicitly
delete specific resources.
Resolves #23
=> Added policy deletion capabilities to the client

Dockerfile.test, bin/needs_publishing, bin/publish_package
There were additional missing things changed:
- `jq` and `curl` were installed
- `pip3` invocation removed a flag that wasn't available on Ubuntu
- ssh key of github is added to known_hosts since it won't be
present in the Ubuntu container and it blocks tag fetching
=> Fixed issues related to conversion of test container to Ubuntu

bin/build_cli_container
This should allow other scripts (like publishing) to anticipate what
image to use. We can't use just `latest` as this will make the runs have
a race condition on builds colocated on the same builder.
=> Tag the CLI image during builds with addition full-version tag

Dockerfile.test
The Python keyring library in 18.04 seems broken so we upgrade it with
the one from PyPI.
Upstream: https://bugs.launchpad.net/usd-importer/+bug/1794041
=> Apply possible workaround for Ubuntu keyring Python bug

Jenkinsfile
This will allow them to run faster and to not block each other on
problems.
=> Make publishing stages run in parallel

docker-compose.yml
Postgres introduced a change that you can't start a pg container without setting a password. They also introduced a new flag named
`POSTGRES_HOST_AUTH_METHOD` that you can set to trust in order to let anyone connect with the db without a password (as we do today). This is ok for our ci and dev envs so this commit adds this env var to all pg containers that didn't have a password set for them
=> Added a fix for the updated PG 9.4 container image

CHANGELOG.md, conjur/http.py, test/test_http.py
This early Python3 version might be used in some setups so we removed
out the auto command that didn't add too much in functionality.
Connected to #43
=> Removed out references to `enum.auto` to support Python 3.5

Jenkinsfile
Changes the trivy scan to do 2 reports - one of just fixable potential vulnerabilites and one with all detected potential vulnerabilities (whether a fix is available or not). Builds will only fail when there is a fix available. I also bumped the build failure threshold so builds will fail on fixable HIGH or CRITICAL vulnerabilities instead of just CRITICAL, as there should be no fixable HIGHs currently. 
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
=> Builds fail only on fixable HIGH or CRITICAL vulns

Jenkinsfile
This will prevent us from hitting issues with the code much earlier
rather than having someone proactively find them.
=> Add nightly build trigger

requirements.txt, setup.py
urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method,
as demonstrated by inserting CR and LF control characters in the first argument of putrequest().
NOTE: this is similar to CVE-2020-26116.
=> Upgrade urllib to 1.25.9+

CHANGELOG.md, conjur/version.py
A release is needed with the latest updates so this change increases the
version to v0.1.1
Connected to: #54
=> Bump version to v0.1.1

setup.py
`setup.py` had a wrong dependency version entered for PyYAML during
version upgrade which this commit fixes.
Resolves #75
=> Fixed typo in PyYAML dependency version bump

Dockerfile
The build is failing because in a previous commit we updated the package name from conjur-cli -> conjur but did not update the Dockerfile that we use to build our image and push to our registry. This change fixes this.
=> Update Dockerfile naming as a result of module rename

conjur/ssl_service.py
When a user runs 'init' command, we open a socket with Conjur, fetch the certificate for them from the Conjur server and save it on their local machine.
We were previously limiting the context to to communicate over TLS 1.2 to fetch the certificate from the Conjur server. This change expands this to also support 1.3 and block anything less than 1.2. This option can now be configured via an environment variable.
=> Expand TLS version communication to 1.2 and 1.3

.github/CODEOWNERS
Updates codeowners in the repo to be Palmtree by default
=> Update CODEOWNERS to Palmtree from Community and Integrations team

release/assets/macos_cli_setup.sh
This PR adds the CLI installation script for macOS environments to the repo. This script will be compressed together with the CLI binaries and delivered to customers in our release page.
Previously the CLI on macOS environments was taking upwards of 15+ seconds on each run. This is because of a security policy on macOS machines that extracts executables and scans them. To account for this, we will pack the CLI as a directory instead of a single executable file and create a symbolic link between the directory and /usr/local/bin. This script hides away these details for the user 
Resolves #126 
Separate issue
=> Add CLI installation script for macOS

CONTRIBUTING.md, bin/build_binary, bin/test_integration, test/test_integration_configurations.py, test/test_integration_credentials.py, test/test_integration_list.py, test/test_integration_oss.py, test/test_integration_policy.py, test/test_integration_resource.py, test/test_integration_variable.py, test/util/test_helpers.py, test/util/test_infrastructure.py, test/util/test_runners/integration_test_case.py, test/util/test_runners/integrations_tests_runner.py, test/util/test_runners/params.py, test/util/test_runners/test_runner_args.py
This PR adds the ability to run our tests as a process. Tests are run using the packed CLI exec, without requiring python on the machine and running against an CLI exec. 
This PR also adds the supporting documentation
To run follow the docs supplied in the PR `./integrations_tests_runner -i test_with_process -u https://conjur-server -a someaccount -l somelogin -p Myp@ssw0rd1! -f /test -c /dist/conjur --invoke_cli_as_process`
Resolves #160 
This PR is a continuation of https://github.com/cyberark/conjur-api-python3/pull/144 and https://github.com/cyberark/conjur-api-python3/pull/129
=> Fix tests to run as process

conjur/host/host_controller.py, conjur/init/init_controller.py, conjur/login/login_controller.py
The readline import was an import added to avoid replacing the line when running CTLR+C to stop a process. This lead to the Windows executable not working on deployment. This PR removes readline traces in the codebase
=> Remove readline import

conjur/cli.py, test/util/test_runners/test_runner_args.py
Makes minor changes as per UX changes demonstrated here in the [UX guide ](https://ljfz3b.axshare.com/#id=x8ktq8&p=conjur_help__init&g=1)
=> Fix title rendering

requirements.txt
A bump in the cryptography indirect dependency lead to cascading breaking changes in our direct dependency pyopenssl. This PR fixes this by directing adding cryptography to our requirements.txt and reverting to a previous cryptography version.
New Release of cryptography version 3.4.1 broke our pipeline. Currently We will use the previous version 3.3.1 and and issue will open to investigate it future https://github.com/cyberark/conjur-api-python3/issues/184
For more reading about the rust problem in new cryptography version you can read in their github page : https://github.com/pyca/cryptography/issues/5771
=> Fix broken pipeline on cryptography dependency

README.md
Made the documentation more clear about giving the pem file path to the sdk. It seemed like a path to folder changed it to bundle.pem so we understand its a file
=> Change bundle path README for clarity

conjur/api/client.py, conjur/cli.py, conjur/controller/init_controller.py, conjur/logic/init_logic.py, test/test_integration_configurations.py, test/test_integration_policy.py, test/test_unit_cli.py, test/test_unit_client.py, test/test_unit_init_controller.py, test/util/test_helpers.py
The purpose of this PR is to enhance the UX for the user when running in insecure mode. Previously the user would have to physically create the conjurrc file if they wanted to run the init in insecure mode b/c the command didnt support this flag. This addition allows the user to run init in insecure mode and get a blank value for the cert_file entry, creating the following conjurrc
```
---
account: cucumber
appliance_url: https://ec2-3-126-247-26.eu-central-1.compute.amazonaws.com
cert_file: ''
plugins: []
```
Resolves -
=> Add ability to run init in insecure mode

conjur/logic/login_logic.py, conjur/wrapper/http_wrapper.py
When a user runs in insecure mode, the conjurrc looked like:
```
---
account: cucumber
appliance_url: https://conjur-server
cert_file: ''
plugins: []
```
When they send a follow-up login command, the empty cert_file was being translated to FALSE. We don't want to make this implicit conclusion and only run in insecure mode if the user declares to do so
=> Fixes the bug where an empty cert_file entry allows for a user to login

conjur/api/client.py, conjur/cli.py, conjur/controller/init_controller.py, conjur/controller/login_controller.py, conjur/controller/user_controller.py, conjur/errors.py, conjur/logic/init_logic.py, conjur/logic/login_logic.py, conjur/wrapper/http_wrapper.py, test/test_config/no_cert_conjurrc, test/test_integration_credentials.py, test/test_unit_cli.py, test/test_unit_client.py, test/test_unit_http.py, test/test_unit_login_controller.py, test/test_unit_login_logic.py, test/test_unit_logout_logic.py, test/test_unit_user_controller.py, test/test_unit_user_logic.py, test/util/test_helpers.py, test/util/test_path_provider.py
When using the CLI in an environment with signed certificates, we are successful in running init, saving the pem to the machine received from the Conjur server and generating the conjurrc. Upon sending a follow-up request (login), the request is failing on CERTIFICATE_VERIFY_FAILED error. This fix adds the signed-certificate flow
At this time we will not add the CA cert flow to our testing infrastructure. There is a [separate ticket for this](https://github.com/cyberark/conjur-api-python3/issues/200)
Resolves #178 
Will be added later
=> Add support for CA signed certificates

conjur/errors_messages.py
The formatting of the MISMATCH_HOSTNAME_MESSAGE is off and this commit fixes that.
=> Update mismatch hostname formatting

Jenkinsfile
We push the CLI and SDK as a single package to PyPi so that users with Python installed can easily pull the CLI for human-use and SDK for application-use. The code for the SDK and CLI are together under a single repo and pushed to PyPi as a single library. Because only the CLI is to be promoted to GA (v7.0.0) we cannot continue to push both the CLI and the SDK together to PyPI and there is no way (at the moment) to separate the artifacts into two different libraries so that the client can remain < v1.0.0.
An [issue](https://github.com/cyberark/conjur-api-python3/issues/211) was open to properly address this.
Resolves -
Will be a separate PR
=> Remove publishing to PyPI (see description for more info)

test/test_integration_resource.py, test/test_unit_logout_controller.py, test/test_unit_logout_logic.py, test/test_unit_user_controller.py, test/test_unit_user_logic.py
Password complexity restriction was a feature introduced in a relatively newer version of Conjur. Before release we need to check against these older server versions and therefore when running the integration tests for change-password, the tests were failing because an error was not being raised and the actual password was being changed which leads to failing tests on future runs. This fixes this by attempting to change the password on a dummy user instead of admin's.
This PR also gives our broken UT build. The instability was coming the way at which the Jenkins pipeline is running the tests. 
Resolves -
=> Update change-password tests to change non-admin passwords and fix failing UTs

conjur/constants.py, conjur/controller/init_controller.py, test/test_integration_configurations.py
We previously only supported 'yes' and 'YES' for confirmation. Now, 'y' and 'Y' are supported.
Resolves -
=> Add support for short-hand 'y' (yes) for confirmation

conjur/api/client.py, conjur/wrapper/keystore_adapter.py
This PR suppresses the third party keyring's logs. 
Previously, we would get a log in debug mode for all loaded keyrings 
```
conjur -d init -u https://sigallb.aim-dev.conjur.net
2021-04-01 08:56:30,043 DEBUG: Loading KWallet
2021-04-01 08:56:30,044 DEBUG: Loading SecretService
2021-04-01 08:56:30,046 DEBUG: Loading Windows
2021-04-01 08:56:30,047 DEBUG: Loading chainer
2021-04-01 08:56:30,048 DEBUG: Loading macOS
2021-04-01 08:56:30,068 DEBUG: Initiating a TLS connection with 'https://sigallb.aim-dev.conjur.net'...
...
```
This removes this and now we get:
```
conjur -d init -u https://sigallb.aim-dev.conjur.net
2021-04-01 08:56:30,068 DEBUG: Initiating a TLS connection with 'https://sigallb.aim-dev.conjur.net'...
```
Resolves #-
=> Suppress keyring logs

CHANGELOG.md, Jenkinsfile, setup.py
Previously we decided that we were not going to push to Pypi because only the CLI is being promoted to GA and the pushed package includes both the CLI and SDK. Now, we changed this decision and will now push to Pypi and detail that the SDK will remain a Community-level project so that all will continue to benefit from the project's developments. 
This commit also adds entries to the CHANGELOG to detail all breaking changes.
Overturns decision to not push to Pypi: https://github.com/cyberark/conjur-api-python3/pull/212/files
Resolves -
=> Enable push to pypi and document breaking changes in SDK

conjur/api/client.py, conjur/controller/init_controller.py, conjur/controller/login_controller.py, conjur/logic/init_logic.py, conjur/util/util_functions.py, conjur/wrapper/http_wrapper.py, test/test_integration_credentials_keyring.py, test/test_unit_client.py, test/test_unit_init_controller.py, test/test_unit_keystore_credentials_provider.py, test/test_unit_login_controller.py
Previously when a user was running in insecure mode and not supplying the url, they would get an error "Invalid URL 'None/info': No schema supplied. Perhaps you meant http://None/info?". This fixes this by extracting the request for the URL from the certificate logic
conjur insecure init 
Returns error
conjur insecure init -u https://conjur-server
Return success
Resolves -
=> Fix bug for prompting user for url in insecure mode

test/test_integration_credentials_netrc.py, test/util/test_runners/integrations_tests_runner.py, test/util/test_runners/test_runner_args.py
removed run_as_process argument. calculate this from if cli-to-test has a path
- Removed unsused setups at the start of integration_test_runner.
- Removed invoke_cli_as_process cmd line arg.
- [-] This PR does not include user-facing changes and doesn't require a CHANGELOG update
- [-] The changes in this PR do not require tests
- [-] This PR does not require updating any documentation
=> Removed unnecessary netrc and conjurrc creation in integration tests

Jenkinsfile
The building of a container was happening only on version bumps which made this inaccessible to the following stages. This reverts the creation of the container to occur on master builds
Resolves #-
=> Fix broken master with version tag

.github/CODEOWNERS
When adding two lines '*', GH only takes the last line. This adds the codeowners on the same line so there will be two codeowner groups for this repo
=> Correct codeowners overwrite

conjur/cli.py
The `account` description for the init command was confusing because it made it seem that we are overriding the actual account on the server when this is not the case. This change clarifies the wording.
Resolves #239
The rest of the items on the list were either previously closed or no longer relevant
=> Update the init account description

conjur/api/client.py, conjur/errors.py, conjur/logic/credential_provider/credential_store_factory.py, conjur/logic/credential_provider/keystore_credentials_provider.py, conjur/wrapper/__init__.py, conjur/wrapper/keystore_wrapper.py, test/test_integration_credentials_keyring.py, test/test_integration_credentials_netrc.py, test/test_unit_client.py, test/test_unit_credential_store_factory.py, test/test_unit_keystore_adapter.py, test/test_unit_keystore_credentials_provider.py
This commit renames KeystoreAdapter -> KeystoreWrapper for the sake of better naming
Resolves -
=> Change class naming from KeystoreAdapter to KeystoreWrapper

CONTRIBUTING.md, README.md
This commit removes the '$' from the code snippets in our docs in response to GHs rollout of the clipboard feature. If those '$' signs remain and a user clicks on the clipboard to copy the command, the '$' will be copied as well.
Resolves #-
=> Remove '$' in code snippets

conjur/api/client.py, conjur/config.py, conjur/data_object/conjurrc_data.py, conjur/errors.py, conjur/errors_messages.py, test/test_config/incorrect_format_conjurrc, test/test_integration_configurations.py, test/test_unit_client.py, test/test_unit_conjurrc_data.py, test/util/test_path_provider.py
When a user doesn't have the correct keys in their conjurrc config file (because of an older version of conjurrc when using the ruby cli), the user gets incomprehensive error. This fixes this by adding error handling and returning a more detailed error message.
Previously:
With this change:
Resolves #292
=> Add error handling when user uses older conjurrc

.gitignore
.key and .crt files are generated when we run our tests suite locally. These files are only relevant locally and only during the lifecycle of the test environment containers. That being said, they shouldn't be pushed. This commit adds these two file extensions (.crt/.key) to the gitignore file so that we don't push them accidentally.
Resolves -
=> Add certificate information to .gitignore file

Jenkinsfile, conjur/api/ssl_client.py
For the past few days the CLI build has been failing on a pylint error 
```
conjur/api/ssl_client.py:49: [W0238(unused-private-member), SSLClient.__connect] Unused private member `SSLClient.__connect(cls, hostname: str, port: int)
```
This is a false positive because we do use `SSL.Connection` that just started to be triggered. This commit fixes this by disabling the pylinter on this line and also tags PalmTree in notifications of broken builds
Resolves -
=> Fix broken build by ignoring linting error

test/configure_test_executor.sh
Although the password is generated, we should not print
it to the log as we may change it in the future to a
real secret (e.g the one from conjurops)
=> Do not echo command with password

Jenkinsfile, bin/test_integration_rhel8, secrets.yml
We prefer to use the admin password from ConjurOps
instead of generating one. This helps us also in the
complexity and also in referring to the password as
a secret
Resolves #301
=> Use admin password from ConjurOps

Dockerfile.test, Dockerfile.test.rhel8
Test Dockerfile now install zlib.
Jenkins build was failing with the following logs in step `RUN pip3 install -r requirements.txt` in Dockerfile.test and Dockerfile.test.rhel8:
```
Building wheels for collected packages: PyInstaller, wrapt
15:12:02    Running setup.py bdist_wheel for PyInstaller: started
15:12:03    Running setup.py bdist_wheel for PyInstaller: finished with status 'error'
15:12:03    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vw8tvcbf/PyInstaller/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp86smhxdipip-wheel- --python-tag cp36:
15:12:03    running bdist_wheel
15:12:03    running build
15:12:03 …
```
=> Fix Dockerfiles for linting

Dockerfile, Dockerfile.publish
Resolves similar Dockerfile build issues as in [conjur-api-python3#323](https://github.com/cyberark/conjur-api-python3/pull/323), this time in the Publish Jenkins stage.
Installs `zlib1g-dev` in `Dockerfile` and `Dockerfile.publish`.
Resolves main branch build failure.
=> Fix Dockerfiles for publishing

conjur/api/api.py, conjur/argument_parser/_host_parser.py, conjur/config.py, conjur/data_object/conjurrc_data.py, conjur/logic/credential_provider/file_credentials_provider.py, conjur/logic/init_logic.py
The host command had a bug under 'examples' section where it was displaying 'change-password' instead of 'rotate-api-key' when host does not support the change-password command. This commit fixes that and also fixes the broken main build on pylint encoding suggestion
Bug:
Fix:
Resolves -
=> Fix host example from command it does not support

conjur/argument_parser/parser_utils.py, conjur/wrapper/http_wrapper.py
The 'main' building was failing Pylint suggestions. This commit fixes the failure by ignoring pylint's suggestions because the formatting of the strings was done purposefully
Resolves -
=> Fix failing build on Pylint suggestion

CONTRIBUTING.md
Recently RHEL 7 testing has been added to the pipeline. Therefore, when prepping for our release, we don't need to run our tests against those environments. This commit updates the release docs to reflect this
Resolves -
=> Update release process with addition of RHEL 7 to pipeline

conjur/api/api.py, conjur/api/client.py, conjur/api/endpoints.py, conjur/argument_parser/_hostfactory_parser.py, conjur/argument_parser/argparse_builder.py, conjur/cli.py, conjur/controller/hostfactory_controller.py, conjur/data_object/create_token_data.py, conjur/logic/hostfactory_logic.py, conjur/wrapper/http_wrapper.py
Create token - vanilla flow
Added menu parser controller logic and data classes
Basic skeleton was created to allow easy entry into task (Addition was made to help screen, appropriate classes were added)
A token can be created after adding a hostfactory policy
[https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-12446](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-12446)
=> Create token vanilla flow 12446

conjur/controller/policy_controller.py, test/test_integration_policy.py
When failing in load policy we'll print the exact error send from the server.
On raising error we'll check the http error response text in addition to the error itself.
[ONYX-12413](https://ca-il-jira.il.cyber-ark.com:8443/secure/RapidBoard.jspa?rapidView=1475&view=detail&selectedIssue=ONYX-12413)
merged.*
changes, or
=> Log full error on policy load failure

Dockerfile.test.rhel8, test/CentOS-Linux-AppStream.repo
The RHEL 8 repository was updated, and we can't use it to install sole necessary components for the RHEL 8 integration tests.
Using 8-stream repository instead
=> Use 8-stream repository on rhel8 integration tests

conjur/argument_parser/_login_parser.py, conjur/controller/host_controller.py, conjur/controller/user_controller.py
CLI UX had some small issues we'd like to fix:
1. In the help of login command we need to provide an example for host not just user: conjur login -i cucumber/host/myapp -p <API_Key>
2. The string for API key rotation should be broken down to 2 lines - one for Successfully rotated, and second with the API key.
Resolves 
CyberArk internal issue link: [ONYX-13435](https://ca-il-jira.il.cyber-ark.com:8443/secure/RapidBoard.jspa?rapidView=1475&view=detail&selectedIssue=ONYX-13435)
merged.*
changes, or
=> CLI UX improvement

conjur/api/client.py, conjur/logic/credential_provider/credential_store_factory.py, conjur/logic/credential_provider/keystore_credentials_provider.py, conjur/util/design_patterns_base_classes/singelton.py, conjur/util/singelton.py, conjur/wrapper/keystore_wrapper.py, test/test_unit_keystore_adapter.py, test/util/test_path_provider.py, test/util/test_runners/integrations_tests_runner.py, test/util/test_runners/params.py
keyStoreWrapper is now must be initialized in order to use.
Motivation is
- Disable logging on creation (more safe since logging could hold sensitive data)
- Part of the client refactor done in [ONYX-14370](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14370)
- Make keyStoreWrapper a not static class
[ONYX-14370](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14370)
changes, or
=> Make keystore_wrapper.py non static class.

conjur/cli.py, conjur/controller/hostfactory_controller.py, conjur/controller/init_controller.py, conjur/controller/policy_controller.py, conjur/controller/user_controller.py, conjur/errors.py, conjur/logic/credential_provider/credential_store_factory.py, conjur/logic/login_logic.py, conjur/logic/user_logic.py, conjur/util/util_functions.py, conjur/wrapper/http_wrapper.py, test/test_integration_configurations.py, test/test_integration_credentials_keyring.py, test/test_integration_policy.py, test/test_unit_http.py, test/test_unit_init_controller.py, test/test_unit_login_controller.py, test/test_unit_policy_controller.py, test/test_unit_user_controller.py, test/test_unit_user_logic.py, test/util/test_helpers.py
http_wrapper should not throw exceptions from its internal
library, `requests`.
Instead, it takes the necessary info from the exceptions and use it
to create new internal exception.
This will allow replacing `requests` lib without impacting code
outside of http_wrapper.
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
Resolves #[relevant …
=> Wrap http exceptions from requests lib with internal exceptions

conjur/api/client.py, conjur/cli.py, conjur/interface/credentials_store_interface.py, conjur/logic/credential_provider/credential_store_factory.py, conjur/logic/credential_provider/file_credentials_provider.py, conjur/logic/credential_provider/keystore_credentials_provider.py, test/test_integration_resource.py, test/test_unit_credential_store_factory.py, test/test_unit_logout_controller.py, test/util/test_helpers.py
create_credential_store function currently returns a tupple. 1. credential_store, 2. the credentials source
credentials source is used for logging and exception details. there is no good reason to return a tuple here.
This pr fix this by returning credential_store instead of tuple, and added api for getting credentials source from  credential_store
- create_credential_store return store only and not store source.
- Added get_store_location in the credential_store to get the store source
changes, or
=> Credential_store_factory.py now return store only.

test/CentOS-Linux-AppStream.repo
In RHEL 8, we need CentOS 8-Stream repository to install dbus-x11 and
gnome-keyring.
We need both BaseOS and AppStream repositories, since they need
packages from both, such as dbus-daemon.
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*At least …
=> Fix RHEL 8 integration tests yum repository

.pylintrc, conjur/wrapper/http_wrapper.py
pipeline linting stage will now require less then 120 chars in line instead of 100
- Added pylintrc file with the configuration
- Extended lien 21 in http_wrapper.py to test pipeline
=> Extend linting check line length to 120

CHANGELOG.md, README.md, conjur/api/api.py, conjur/api/client.py, conjur/api/errors.py, conjur/api/models/__init__.py, conjur/api/models/ssl_verification_metadata.py, conjur/api/models/ssl_verification_mode.py, conjur/cli.py, conjur/data_object/conjurrc_data.py, conjur/data_object/credentials_data.py, conjur/util/util_functions.py, test/test_unit_api.py, test/test_unit_cli.py, test/test_unit_client.py, test/test_unit_utils.py
Client will be initialized with less parameters and specific, with a SslVerificationMetaData struct that holds the sslVerification data. This struct should be drilled down to the http_wrapper.
- Added SslVerificationMetaData struct
- Changed constructor in both client and api
- Added functionality to create client from conjurrc (instead of the old way which was done inside the class constructor)
Resolves [ONYX-14370](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14370)
* Client could accept ssl_verification_meta_data object and all functionality will work
changes, or
=> Client to work with ssl verification modes

test/host_factory/test_integration_hostfactory.py, test/host_factory/test_integration_hostfactory_token.py
In hostfactory tests, instead of asserting expiration as regex, assert
it explicitly as time object and allow up to 10 seconds difference from
expected result.
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*At least 1 todo must be completed in …
=> Fix flaky hostfactory integration tests

CHANGELOG.md, README.md
added link to SDK repo
SDK is now leaving under a different repo.
we should remove it from our docs and add reference to it in the README.md file
- Removed sdk content from readme
- Added link to SDK repo
- Updated changelog
changes, or
=> Remove sdk content from readme

test/test_integration_resource.py
Fixes test broken by https://github.com/cyberark/conjur/pull/2529
- Changed expected status code from 401 to 404
N/A
changes, or
=> Update integration test with new status code

design/authn-ldap.md
Add design document for authn-ldap support in the CLI and API.
CyberArk internal issue link: [ONYX-20237](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-20237)
=> Add authn-ldap design spec

CHANGELOG.md, conjur/config.py, conjur/data_object/conjurrc_data.py, conjur/errors_messages.py, test/test_config/bad_cert_conjurrc, test/test_config/good_conjurrc, test/test_config/incorrect_format_conjurrc, test/test_config/missing_url_conjurrc, test/test_config/no_cert_conjurrc, test/test_config/no_cert_localhost_conjurrc, test/test_integration_oss.py, test/test_unit_conjurrc_data.py, test/test_unit_init_logic.py, test/util/models/configfile.py, test/util/test_helpers.py
Update the Python CLI to use the older names for the keys in the conjurrc file. This means changing conjur_account => account and conjur_url => appliance_url.
When reading or writing .conjurrc:
- `conjur_account` is now `account`
- `conjur_url` is now `appliance_url`
For now we are still supporting the old keys when *reading* the conjurrc in order not to break existing installations of the 7.x CLI. This is deprecated and will be removed in a future release.
This fixes incompatibility between this Python CLI and the previous
Ruby/Docker based CLI, as well as summon-conjur.
The variable names remain the same. Only the key names are changed.
CyberArk internal issue link: [ONYX-22955](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-22955)
changes, or
=> Revert conjurrc key names to match Ruby CLI

CHANGELOG.md, conjur/argument_parser/_show_parser.py, conjur/argument_parser/argparse_builder.py, conjur/cli.py, conjur/cli_actions.py, conjur/controller/list_controller.py, conjur/controller/show_controller.py, conjur/logic/show_logic.py, conjur/util/util_functions.py, test/test_config/show_policy.yml, test/test_integration_show.py, test/test_unit_cli.py, test/test_unit_init_logic.py, test/test_unit_show_controller.py, test/test_unit_show_logic.py, test/util/test_infrastructure.py
Depends on https://github.com/cyberark/conjur-api-python/pull/31
Add the "show" command which existed in the [Ruby CLI](https://github.com/cyberark/cyberark-conjur-cli-docker-based/blob/main/lib/conjur/command/resources.rb#L23) but was not added to the Python CLI.
Added support for command with syntax `conjur show -i variable:path/to/var`
Resolves #218
CyberArk internal issue link: [ONYX-23088](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23088)
changes, or
=> Add "show" command

CHANGELOG.md, conjur/argument_parser/_init_parser.py, conjur/argument_parser/_role_parser.py, conjur/argument_parser/_show_parser.py, conjur/argument_parser/argparse_builder.py, conjur/cli.py, conjur/cli_actions.py, conjur/controller/__init__.py, conjur/controller/role_controller.py, conjur/logic/__init__.py, conjur/logic/role_logic.py, conjur/resource.py, conjur/role.py, test/test_integration_role.py, test/test_unit_cli.py, test/test_unit_role_logic.py
Depends on https://github.com/cyberark/conjur-api-python/pull/30
Add the Role command and `exists` subcommand which existed in the [Ruby CLI](https://github.com/cyberark/cyberark-conjur-cli-docker-based/main/lib/conjur/command/roles.rb#L24) but was not added to the Python CLI.
Added support for command with syntax `conjur role exists -i someuser -k user`
CyberArk internal issue link: [ONYX-23085](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23085)
changes, or
=> Add Role exists command

CHANGELOG.md, conjur/argument_parser/_role_parser.py, conjur/cli_actions.py, conjur/controller/role_controller.py, conjur/logic/role_logic.py, test/test_config/role_policy.yml, test/test_integration_role.py, test/test_unit_cli.py, test/test_unit_role_controller.py, test/test_unit_role_logic.py, test/util/test_infrastructure.py
Add support for the 'role memberships' command that previously existing in the Ruby CLI.
Add CLI functionality that allows commands with the syntax `conjur role memberships -i user:someuser`.
Support both recursive (default) and direct membership queries (-d / --direct). Drop support for the --system flag which served no purpose.
CyberArk internal issue link: [ONYX-23087](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23087)
merged.*
changes, or
=> Add role memberships command

conjur/logic/resource_logic.py, conjur/logic/role_logic.py, test/test_unit_cli.py, test/test_unit_role_logic.py
Depends on https://github.com/cyberark/conjur-api-python/pull/35
Refactored the "role exists" command to use the new `role_exists` method in the API library which has a smaller network footprint and handles the different status codes for us.
N/A
changes, or
=> Use new `role_exists` API method

conjur/controller/init_controller.py, test/test_integration_configurations.py, test/util/test_helpers.py
- Added fixes to the 'init' command to omit empty string paths for Ruby CLI compatibility
- Updated files to remove empty string declarations
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-24956
=> Updates 'init' command's cert_file property

README.md
There's a warning on the README so that Windows users can learn that the CLI persists login status across sessions by default. Communicate the work-arounds of logging out after each session, or setting the KEYRING_PROPERTY_PERSIST environment variables. 
Added Security section to README.md
=> Add warning that Windows users persist login status

Dockerfile.test.rhel8, bin/test_integration, bin/test_integration_rhel, test/list_resources/test_integration_list.py, test/test_integration_user_host.py
Integration tests are failing due to Conjur changes introduced in
Conjur [2755](https://github.com/cyberark/conjur/pull/2755)
Updated the tests to account for the admin changes
Resolves # N/A
CyberArk internal issue ID: CNJR-2172
merged.*
changes, or
=> Update tests due to Conjur adding admin user
